# Generated by Django 3.2.5 on 2021-07-30 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='status',
            field=models.CharField(blank=True, choices=[('p', 'published'), ('d', 'draft')], max_length=10, null=True),
        ),
    ]
