# Generated by Django 3.2.5 on 2021-08-02 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20210730_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='status',
            field=models.CharField(choices=[('p', 'published'), ('d', 'draft'), ('i', 'pending'), ('r', 'rejected')], default='d', max_length=10),
        ),
    ]
