# Generated by Django 3.2.5 on 2021-08-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0021_auto_20210817_1930'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='rates',
        ),
    ]
