# Generated by Django 3.2.5 on 2021-07-09 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0002_alter_article_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='sub_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
