# Generated by Django 3.2.5 on 2021-07-12 15:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0005_alter_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='writer_source',
            field=models.URLField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='first.category'),
        ),
    ]
