# Generated by Django 3.2.5 on 2021-07-12 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('first', '0006_auto_20210712_1932'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='writer_source',
            new_name='reference',
        ),
        migrations.AlterField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(blank=True, null=True, related_name='articles', to='first.Category'),
        ),
    ]
